### ISSUE TITLE
Any examples?

### ISSUE THREAD

**Issue by ryananthonydrake** [kaspernj/bootstrap-tabs-dynamic#1]
Could you please host an example of your small library working, or try to have a functioning JS Fiddle or domain with an example?

I'd love to see this in action, as I'd like to implement this in a project I'm working on.

Cheers

**Comment by nick322** [comment]
I try to have a functioning JS Fiddle.

http://jsfiddle.net/0ua2gzyc/

**Comment by kaspernj** [comment]
@nick322 I have added your Fiddle to the README.
